//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FationShop.Areas.Admin.Framework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        [Display(Name ="Ngày đặt hàng")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [Display(Name = "Mã khách hàng")]
        public Nullable<int> CustomerID { get; set; }
        [Display(Name = "Tên khách hàng")]
        public string ShipName { get; set; }
        [Display(Name = "Địa chỉ nhận hàng")]
        public string ShipAddress { get; set; }
        [Display(Name = "Số điện thoại nhận hàng")]
        public string ShipPhoneNumber { get; set; }
        [Display(Name = "Email")]
        public string ShipEmail { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
