//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FationShop.Areas.Admin.Framework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        public string Name { get; set; }
        [Display(Name = "SEO")]
        [Required(ErrorMessage = "SEO không được để trống")]
        public string MetaTitle { get; set; }
        [Display(Name = "Mã sản phẩm")]
        [Required(ErrorMessage = "Mã sản phẩm không được để trống")]
        public string Code { get; set; }
        [Display(Name = "Giới thiệu")]
        public string Description { get; set; }
        [Display(Name = "Ảnh sản phẩm 1")]
        public string Image1 { get; set; }
        [Display(Name = "Ảnh sản phẩm 2")]
        public string Image2 { get; set; }
        public HttpPostedFileBase ImageFile1 { get; set; }
        public HttpPostedFileBase ImageFile2 { get; set; }
        public string MoreImage { get; set; }
        [Display(Name = "Giá bán")]
        [Required(ErrorMessage = "Giá bán không được để trống")]
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> Quantity { get; set; }
        [Display(Name = "Mã loại sản phẩm")]
        [Required(ErrorMessage = "Mã loại sản phẩm không được để trống")]
        public Nullable<int> CategoryID { get; set; }
        [AllowHtml]
        [Display(Name = "Chi tiết")]
        public string Detail { get; set; }
        public string Size { get; set; }
        [Display(Name = "Trạng thái hiển thị")]
        public Nullable<bool> Status { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
